#!/bin/bash
PROJECT_DIR="$1"
GIT_URL="$2"

if [[ "$PROJECT_DIR" = "" || "$GIT_URL" = "" ]]; then
	echo "Usage: ./create_project <DIR> <GIT_URL>"
	exit 1
fi

set -e

project_dir_parent=`dirname "$PROJECT_DIR"`
fstype=`df -T "$project_dir_parent" | tail -n 1 | awk '{ print $2 }'`
if [[ "$fstype" == vmhgfs || "$fstype" == vboxfs ]]; then
	echo "You cannot put the project dir in a VMWare or VirtualBox shared folder."
	exit 1
fi
if [[ `whoami` != root ]]; then
	echo "You must run this program as root."
	exit 1
fi

set -x

mkdir -p "$PROJECT_DIR"
chown psg_rpm_automation:psg_rpm_automation_container "$PROJECT_DIR"
chmod u=rwx,g=x,o= "$PROJECT_DIR"

mkdir "$PROJECT_DIR/container"
mkdir "$PROJECT_DIR/container/root"
echo "$GIT_URL" > "$PROJECT_DIR/container/root/git_url"
chown -R psg_rpm_automation_container:psg_rpm_automation_container "$PROJECT_DIR/container"
chmod u=rwx,g=,o= "$PROJECT_DIR/container"

mkdir "$PROJECT_DIR/log"
chown psg_rpm_automation:psg_rpm_automation "$PROJECT_DIR/log"
