#!/bin/bash
PROJECT_DIR="$1"
GIT_URL="$2"

if [[ "$PROJECT_DIR" = "" || "$GIT_URL" = "" ]]; then
	echo "Usage: ./create_project <DIR> <GIT_URL>"
	exit 1
fi

set -e

CONTAINER_APP_UID=9999

set -x

mkdir -p "$PROJECT_DIR"
echo "$GIT_URL" > "$PROJECT_DIR/git_url"
chown -R $CONTAINER_APP_UID:$CONTAINER_APP_UID "$PROJECT_DIR"
