#!/bin/bash
PROJECT_DIR="$1"
COMMAND="$2"
shift
shift

if [[ "$PROJECT_DIR" = "" || "$COMMAND" = "" ]]; then
	echo "Usage: ./invoke <PROJECT_DIR> <COMMAND> [ARGS]"
	exit 1
fi

set -e
BASE_DIR=`dirname "$0"`
BASE_DIR=`cd "$BASE_DIR"; pwd`
exec docker run -privileged -rm \
	-v "$PROJECT_DIR/container/root:/project" \
	-v "$BASE_DIR/scripts:/scripts:ro" \
	-v "$BASE_DIR/rpm-nginx:/rpm-nginx:ro" \
	phusion/passenger_rpm_automation \
	sudo -u app -H "/scripts/$COMMAND" "$@"
