#!/bin/bash
set -e
SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`
exec docker run --rm --privileged -t -i \
	-v "$SELFDIR:/system:ro" \
	"$@" \
	phusion/passenger_rpm_automation \
	/system/internal/my_init --skip-runit --skip-startup-files --quiet -- \
	/bin/bash
