#!/bin/bash
# Build RPM packages for the given git commit
set -e
source /scripts/_config

BUILD_PASSENGER=1
BUILD_NGINX=0

while getopts c:t:pnh opt; do
	case $opt in
	c)
		export GIT_COMMIT=$OPTARG
		;;
	t)
		export GIT_TAG=$OPTARG
		;;
	p)
		BUILD_PASSENGER=1
		BUILD_NGINX=0
		;;
	n)
		BUILD_PASSENGER=0
		BUILD_NGINX=1
		;;
	h)
		echo "Usage: ./invoke <PROJECT_DIR> build [options...]"
		echo "Build RPM packages."
		echo
		echo "Options:"
		echo "  -c COMMIT    Use this specific git commit"
		echo "  -t TAG       Use this specific git tag"
		echo "  -p           Build only Passenger RPMs"
		echo "  -n           Build only Nginx RPMs"
		exit
		;;
	\?)
		exit 1
		;;
	esac
done

function reset_stage_log()
{
	echo -n > /project/build_stage
}

function log_stage()
{
	local name="$1"
	echo "`date` -- $name" >> /project/build_stage
}

function install_doctools()
{
	rake test:install_deps DEVDEPS_DEFAULT=false DOCTOOLS=true
}

set -x

shopt -s dotglob
reset_stage_log
rm -rf /project/rpms/*
rm -rf ~/rpmbuild/RPMS/* ~/rpmbuild/SRPMS/*

log_stage "Checking out git repo"
/scripts/git_update
cd /project/git
export PASSENGER_DIR=/project/git

if [[ "$BUILD_PASSENGER" = 1 ]]; then
	log_stage "Building Passenger RPMs"
	drake -j$CONCURRENCY rpm:all
else
	log_stage "Building Passenger sources"
	drake -j$CONCURRENCY rpm:sources
fi

if [[ "$BUILD_NGINX" = 1 ]]; then
	log_stage "Building Nginx RPMs"
	mkdir /tmp/rpms
	rake -f /scripts/_build_nginx.rake rpm:all
fi

log_stage "Saving RPMs"
for DIR in pkg/*; do
	if [[ -d "$DIR" ]]; then
		name=`basename "$DIR"`
		mkdir /project/rpms/$name
		cp "$DIR"/*.rpm /project/rpms/$name/
		createrepo /project/rpms/$name
	fi
done
