#!/bin/bash
# Clone or update git repo
set -e
source /scripts/_config

while getopts c:t:h opt; do
	case $opt in
	c)
		export GIT_COMMIT="$OPTARG"
		;;
	t)
		export GIT_TAG="$OPTARG"
		;;
	h)
		echo "Usage: ./invoke <PROJECT_DIR> git_update [options...]"
		echo
		echo "Options:"
		echo "  -c COMMIT    Use this specific git commit"
		echo "  -t TAG       Use this specific git tag"
		exit
		;;
	\?)
		exit 1
		;;
	esac
done

function can_switch()
{
	[[ "$GIT_COMMIT" != "" || "$GIT_TAG" != "" ]]
}

function switch_to_commit()
{
	if [[ "$GIT_COMMIT" != "" ]]; then
		git reset --hard "$GIT_COMMIT"
	else
		git reset --hard "$GIT_TAG"
	fi
}

set -x

if [[ -e /project/git ]]; then
	cd /project/git
	rm -rf *
	git fetch
	if can_switch; then
		switch_to_commit
	else
		git reset --hard origin/master
	fi
else
	git_url=`cat /project/git_url`
	git clone "$git_url" /project/git
	if can_switch; then
		switch_to_commit
	fi
fi
