#!/bin/bash
set -e
source /scripts/_config

while getopts c:t:h opt; do
	case $opt in
	c)
		export GIT_COMMIT=$OPTARG
		;;
	t)
		export GIT_TAG=$OPTARG
		;;
	h)
		echo "Usage: ./invoke <PROJECT_DIR> build [options...]"
		echo
		echo "Options:"
		echo "  -c COMMIT    Use this specific git commit"
		echo "  -t TAG       Use this specific git tag"
		exit
		;;
	\?)
		exit 1
		;;
	esac
done

set -x

/scripts/git_update
cd /project/git

sudo tee /etc/sudoers.d/gem_home <<EOF
Defaults env_keep += "GEM_HOME"
Defaults env_keep += "GEM_PATH"
EOF
sudo chmod 440 /etc/sudoers.d/gem_home

# Test _preprocess_nginx_specfile, which depends on the Passenger sources
/scripts/_preprocess_nginx_specfile . \
	/rpm-nginx/nginx.spec.template \
	> /tmp/nginx.spec

exec ./dev/test_rpm_packaging.sh
