#!/bin/bash
# Test RPM packaging for the given git commit
set -e
source /scripts/_config

while getopts c:t:h opt; do
	case $opt in
	c)
		export GIT_COMMIT=$OPTARG
		;;
	t)
		export GIT_TAG=$OPTARG
		;;
	h)
		echo "Usage: ./invoke <PROJECT_DIR> test [options...]"
		echo "Test RPM packaging."
		echo
		echo "Options:"
		echo "  -c COMMIT    Use this specific git commit"
		echo "  -t TAG       Use this specific git tag"
		exit
		;;
	\?)
		exit 1
		;;
	esac
done

set -x

/scripts/git_update
cd /project/git

sudo tee /etc/sudoers.d/gem_home <<EOF
Defaults env_keep += "GEM_HOME"
Defaults env_keep += "GEM_PATH"
EOF
sudo chmod 440 /etc/sudoers.d/gem_home

exec ./dev/test_rpm_packaging.sh
