#!/bin/bash
set -e

/system/internal/inituidgid

# Import signing key.
/system/internal/setuser app /tools/silence-unless-failed \
  gpg --batch --trust-model always --import /params/signing_key

# Make GPG non-interactive.
mv /usr/bin/gpg2 /usr/bin/gpg2.real
rm /usr/bin/gpg
cp /system/internal/dummygpg /usr/bin/gpg

exec /system/internal/setuser app \
  rpm --resign --define '%_signature gpg' --define "%_gpg_name $SIGNING_KEY" \
  /packages/*/*.rpm
