require_relative 'rakefile_support'
require_relative '../lib/tracking'

initialize_rakefile!
initialize_tracking_database!(SHOW_OVERVIEW_PERIODICALLY)


##### Source tarballs and initialization #####

register_tracking_category(:preparation, 'Preparation')

namespace :source do
  DISTROS.each do |distro|
    register_tracking_task(:preparation, "passenger:#{distro}")
    desc "Fetch Passenger source tarball"
    task("passenger:#{distro}") do
      track_task(:preparation, "passenger:#{distro}") do |task|
        passenger_srpm_name=passenger_srpm_name(distro, "*")
        if FETCH_PASSENGER_TARBALL_FROM_CACHE && !Dir["/cache/#{passenger_srpm_name}"].empty?
          cp Dir["/cache/#{passenger_srpm_name}"].first, RPM_SOURCES_DIR
        else
          task.sh "./fetch-passenger-source-tarball.sh #{RPM_SOURCES_DIR} #{distro}"
          cp Dir["#{RPM_SOURCES_DIR}/#{passenger_srpm_name}"].first, "/cache"
        end
      end
    end
  end
end


##### Source RPMs #####

register_tracking_category(:srpm, 'Building source RPMs')

namespace :srpm do
  ### Passenger ###

  desc "Build Passenger SRPMs for all distributions"
  task "passenger:all"

  DISTROS.each do |distro_id|
    distro = DISTRO_BUILD_PARAMS[distro_id]

    task "passenger:all" => "passenger:#{distro_id}"

    register_tracking_task(:srpm, "passenger:#{distro_id}")
    desc "Build Passenger SRPM for #{distro[:name]}"
    task("passenger:#{distro_id}" => [ "source:passenger:#{distro_id}" ]) do
      track_task(:srpm, "passenger:#{distro_id}") do |task|
        task.sh "./update-source-rpm.sh",
                RPM_SOURCES_DIR: RPM_SOURCES_DIR,
                RPM_SPECS_DIR: RPM_SPECS_DIR,
                RPM_SRPMS_DIR: RPM_SRPMS_DIR,
                DISTRO_ID: distro_id,
                ROCKY_NGINX_VERSION: latest_nginx_release(distro_id, :rocky),
                ALMA_NGINX_VERSION: latest_nginx_release(distro_id, :alma),
                RHEL_NGINX_VERSION: latest_nginx_release(distro_id, :rhel)
      end
    end
  end
end


##### Binary RPMs #####

register_tracking_category(:rpm, 'Building binary RPMs')

namespace :rpm do
  desc "Build RPMs for all distributions"
  task :all

  ### Passenger ###

  desc "Build Passenger RPMs for all distributions"
  task "passenger:all"

  DISTROS.each do |distro_id|
    distro = DISTRO_BUILD_PARAMS[distro_id]

    task "all" => "^rpm:passenger:#{distro_id}:#{RPM_ARCH}"
    task "passenger:all" => "^rpm:passenger:#{distro_id}:#{RPM_ARCH}"
    register_tracking_task(:rpm, "passenger:#{distro_id}:#{RPM_ARCH}")

    desc "Build Passenger RPM for #{distro[:name]}, #{RPM_ARCH}"
    task("passenger:#{distro_id}:#{RPM_ARCH}" => [ "srpm:passenger:#{distro_id}" ]) do
      track_task(:rpm, "passenger:#{distro_id}:#{RPM_ARCH}") do |task|
        mock_chroot_name = "#{distro[:mock_chroot_name]}-#{RPM_ARCH}"
        File.write("/etc/mock/#{mock_chroot_name}.cfg", "config_opts['module_setup_commands'] = [ ('enable', 'nginx:#{latest_nginx_module(distro_id, :rocky)}') ]", mode: 'a+') unless distro_id == 'el10'
        recursive_find_string_in_config("/etc/mock/#{mock_chroot_name}.cfg", "[appstream]").each do |file|
          gsub_file(file, 'mirrorlist' => '#mirrorlist', '#baseurl' => 'baseurl')
        end
        srpm=Dir["/work/#{distro_id}-#{RPM_ARCH}/#{PASSENGER_RPM_NAME}*#{distro_id}*.src.rpm"].first
        task.sh "/usr/bin/mock --verbose #{MOCK_FLAGS} " +
                "-r #{mock_chroot_name} " +
                "--resultdir '/work/#{distro_id}-#{RPM_ARCH}' " +
                "--uniqueext passenger-#{distro_id}-#{RPM_ARCH} " +
                "--enable-plugin=ccache " +
                "--rebuild #{srpm}"
      end
    end
  end
end


##### Misc #####

task :clear_work_dir do
  sh "rm -rf /work/*"
end

task :start do
  initialize_tracking_database_logs!
end

task :finish do
  puts
  puts "Finished"
  TRACKING_DB.monitor.synchronize do
    TRACKING_DB.set_finished!
    dump_tracking_database
  end

  puts
  puts "Committing build products to output directory..."
  sh "rm -rf /output/*"
  DISTROS.each do |distro_id|
    rpms = Dir["/work/#{distro_id}-*/nginx-mod-http-*.rpm"]
    srpms = Dir["/work/#{distro_id}-*/*.src.rpm"]
    debuginfo = Dir["/work/#{distro_id}-*/[np]*-debuginfo*.rpm"]
    files = rpms + srpms + debuginfo
    if files.any?
      sh "mkdir -p /output/#{distro_id}"
      cp files, "/output/#{distro_id}/"
    end
  end
end
