ROOT = File.absolute_path(File.dirname(__FILE__))

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.hostname = "vmtest7"

  config.vm.synced_folder File.absolute_path("#{ROOT}/../../.."), "/vagrant"

  if File.exist?("#{ROOT}/../../../../bin/passenger")
    passenger_path = File.absolute_path("#{ROOT}/../../../../bin/passenger")
  elsif File.directory?("#{ROOT}/../../../../passenger")
    passenger_path = File.absolute_path("#{ROOT}/../../../../passenger")
  end
  if passenger_path
    config.vm.synced_folder passenger_path, "/passenger"
  end

  config.vm.provider :virtualbox do |vb, override|
    vb.cpus   = 2
    vb.memory = 1024
  end

  config.vm.provider :vmware_fusion do |vf, override|
    vf.vmx["numvcpus"] = 2
    vf.vmx["memsize"]  = 1024
  end

  config.vm.provision :shell, :path => "setup.sh"
end
